### PR TITLE
Use the nginx_refactoring branch of the modsecurity repository.

### PR DESCRIPTION
**Pull request by danabr**
This branch contains numerous stability fixes for the modsecurity nginx port.

### CODE REVIEW

**Comment by danabr** [comment]
We have at least one way to reproduce a memory-leak followed by a nginx worker process crash with the 2.9.0 version of modsecurity. That particular case was fixed by switching to this branch.

**Comment by sbagmeijer** [comment]
Hi I slightly need to think about this, I just closed a change where people said I should not build directly from github as things can be unstable see issue #4 and #5 , if I would do this change I kind of go back what I just fixed for all packages.

Perhaps I can make a secondary version compiled from github like I do with some of my other packages such as (ulyaoth-nginx-naxsi-masterbuild) for example.

**Comment by sbagmeijer** [comment]
I am in the progress of making up to date 2.9.0-2 version, I will leave the spec file as it is for now so I can updated it correctly with the next official release.

I will build it temporarily for now with the special nginx branch as your recommended.

**Comment by sbagmeijer** [comment]
Packages should be tomorrow in the repository as my build servers are currently running a new hhvm version and that takes a few hours :).

Thank you again for the help with this if you see anything else that could be improved please let me know I really appreciate the help!

**Comment by sbagmeijer** [comment]
New rpms are now online: https://www.ulyaoth.net/resources/modsecurity-nginx.23/updates

**Comment by danabr** [comment]
Great, thanks!

**Pull request merged**
